homeassistant:
  name: Home
  latitude: !secret latitude_secret
  longitude: !secret longitude_secret
  elevation: 669
  unit_system: metric
  time_zone: America/Edmonton
  customize: !include customize.yaml
  

http:
  api_password: !secret http_password

# Track the sun
sun:

# Enables the frontend
frontend:

hassio:
# Logger level
# logger:
  # default: critical

# Cloud stuff
# cloud:
config:

# Checks for available updates
updater:

# Show links to resources in log and frontend
# introduction:

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - binary_sensor.back_door_sensor
      - binary_sensor.basement_nest_protect_online
      - binary_sensor.basement_window_sensor
      - binary_sensor.entryway_camera_entryway__zone_1_activity
      - binary_sensor.entryway_camera_entryway_motion_detected
      - binary_sensor.entryway_camera_entryway_online
      - binary_sensor.entryway_camera_entryway_sound_detected
      - binary_sensor.entryway_nest_protect_online
      - binary_sensor.front_door_sensor
      - binary_sensor.garage_door_sensor
      - binary_sensor.hallway_thermostat_fan
      - binary_sensor.hallway_thermostat_has_leaf
      - binary_sensor.hallway_thermostat_is_locked
      - binary_sensor.hallway_thermostat_is_using_emergency_heat
      - binary_sensor.hallway_thermostat_online
      - binary_sensor.home_basement_nest_protect_co_detected
      - binary_sensor.home_basement_nest_protect_smoke_detected
      - binary_sensor.home_entryway_nest_protect_co_detected
      - binary_sensor.home_entryway_nest_protect_smoke_detected
      - binary_sensor.hub_hub
      - binary_sensor.overflow_drain_liquid_detected
      - binary_sensor.wink_relays_top_button_hub
      - binary_sensor.hallway_nest_protect_online
      - binary_sensor.home_basement_nest_protect_co_severity
      - binary_sensor.home_basement_nest_protect_smoke_severity
      - binary_sensor.home_entryway_camera_entryway_capturing_audio
      - binary_sensor.home_entryway_camera_entryway_capturing_video
      - binary_sensor.home_entryway_camera_entryway_loudness
      - binary_sensor.home_entryway_camera_entryway_motion
      - binary_sensor.home_entryway_nest_protect_co_severity
      - binary_sensor.home_entryway_nest_protect_smoke_severity
      - binary_sensor.home_hallway_nest_protect_co_detected
      - binary_sensor.home_hallway_nest_protect_co_severity
      - binary_sensor.home_hallway_nest_protect_smoke_detected
      - binary_sensor.home_hallway_nest_protect_smoke_severity
      - binary_sensor.home_nursery_camera_nursery_capturing_audio
      - binary_sensor.home_nursery_camera_nursery_capturing_video
      - binary_sensor.home_nursery_camera_nursery_loudness
      - binary_sensor.home_nursery_camera_nursery_motion
      - camera.entryway
      - camera.living_room
      - group.all_automations
      - group.all_devices
      - group.all_lights
      - group.all_locks
      - group.all_scripts
      - group.automations
      - group.default_view
      - group.family
      - group.general
      - group.kitchen
      - group.lights
      - group.living_room
      - group.master_bedroom
      - group.media_room
      - group.nest_co_status
      - group.nest_smoke_status
      - group.nursery
      - group.rooms
      - group.scheduled_lights
      - group.sensors
      - media_player.basement_roku
      - media_player.basement_players
      - media_player.bedroom_players
      - media_player.living_room_players
      - media_player.nexus_7_2012
      - sensor.basement_nest_protect_battery_health
      - sensor.entryway_nest_protect_battery_health
      - sensor.hallway_thermostat_humidity
      - sensor.hallway_thermostat_hvac_state
      - sensor.hallway_thermostat_operation_mode
      - sensor.hallway_thermostat_target
      - sensor.hallway_thermostat_temperature
      - sensor.megaplex
      - sun.sun
      - sensor.pws_alerts
      - sensor.pws_dewpoint_c
      - sensor.pws_dewpoint_string
      - sensor.pws_elevation
      - sensor.pws_feelslike_c
      - sensor.pws_feelslike_string
      - sensor.pws_heat_index_c
      - sensor.pws_heat_index_string
      - sensor.pws_location
      - sensor.pws_observation_time
      - sensor.pws_precip_1hr_metric
      - sensor.pws_precip_1hr_string
      - sensor.pws_precip_today_in
      - sensor.pws_precip_today_metric
      - sensor.pws_precip_today_string
      - sensor.pws_pressure_in
      - sensor.pws_pressure_mb
      - sensor.pws_pressure_trend
      - sensor.pws_relative_humidity
      - sensor.pws_solarradiation
      - sensor.pws_station_id
      - sensor.pws_temp_c
      - sensor.pws_temperature_string
      - sensor.pws_uv
      - sensor.pws_visibility_km
      - sensor.pws_weather
      - sensor.pws_wind_degrees
      - sensor.pws_wind_dir
      - sensor.pws_wind_gust_kph
      - sensor.pws_wind_kph
      - sensor.pws_wind_string
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature

# Enables support for tracking state changes over time.
history:

# Discover some devices automatically
# discovery:

group: !include groups.yaml

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

#sensors
sensor: !include sensors.yaml

# Wink
wink:
  # email: !secret wink_email
  # password: !secret wink_password
  local_control: True

#IFTTT
ifttt:
  key: !secret ifttt_key

#Media Players (Plex)
media_player:
  - platform: plex
  # Living Room - v2
  # - platform: cast
    # host: 192.168.2.194
  # nursery - LG Music Flow H3
  # - platform: cast
    # host: 192.168.2.239
  # kitchen - Google Home
  # - platform: cast
    # host: 192.168.2.205
  # Nexus Player
  # - platform: cast
    # host: 192.168.2.79
  # Chromecast Audio
  # - platform: cast
    # host: 192.168.2.192
  # Bedroom Roku 3
  # - platform: roku
    # host: 192.168.2.99
  # Living Room Roku 3
  # - platform: roku
    # host: 192.168.2.107
  # Basement Roku 3
  # - platform: roku
    # host: 192.168.2.55
  - platform: universal
    name: Basement Players
    children:
      # - media_player.basement
      - media_player.basement_roku
      # - media_player.my_nexus_player
      # - media_player.roku_1gs3a2056551
  - platform: universal
    name: Living Room Players
    children:
      # - media_player.living_room
      - media_player.living_room_roku
  - platform: universal
    name: Bedroom Players
    children:
      # - media_player.bedroom
      - media_player.bedroom_roku
  # - platform: vlc
    # name: speaker_1
    # arguments: '--alsa-audio-device=hw:1,0'

#pushbullet
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key
    name: mypushbullet
  - platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
    name: mypushover

#Input Selects
input_select:
  arm_alarm:
    name: Set Alarm
    options:
     - Keep Disarmed
     - Arm Capable
    initial: Arm Capable
    icon: mdi:alarm-check
  brendan_status_dropdown:
    name: Brendan
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  heather_status_dropdown:
    name: Heather
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

#Input Boolean
input_boolean:
  alarm_state:
    name: Alarm State
    initial: off
    icon: mdi:bell

# Zwave Hub
# zwave:
  # usb_path: /dev/ttyACM0
  # config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  # polling_interval: 30000
  # new_entity_ids: false
  
#asus router for device tracker
device_tracker:
  platform: asuswrt
  host: 192.168.2.1
  protocol: ssh
  username: !secret asuswrt_user
  password: !secret asuswrt_password
  track_new_devices: no
  interval_seconds: 5
  consider_home: 600

camera:
  - platform: nest

scene: !include scenes.yaml

automation: !include automations.yaml

script: !include scripts.yaml

alert: !include alerts.yaml

tts:
  - platform: google

# vacuum:
  # - platform: roomba
    # host: 192.168.2.186
    # username: !secret roomba_blid_secret
    # password: !secret roomba_password_secret
    # name: Geoffrey
cover:
  - platform: myq
    username: !secret myq_email
    password: !secret myq_password
    type: chamberlain

light:
  - platform: template
    lights:
      garage_door_opener:
        friendly_name: "Garage Door Opener"
        value_template: "{{ is_state('cover.garage_door_opener', 'open') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.garage_door_opener
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.garage_door_opener
      front_door_lock:
        friendly_name: "Front Door Lock"
        value_template: "{{ is_state('lock.front_door_locked_10', 'locked') }}"
        turn_on:
          service: lock.lock
          data:
            entity_id: lock.front_door_locked_10
        turn_off:
          service: lock.unlock
          data:
            entity_id: lock.front_door_locked_10
      back_door_lock:
        friendly_name: "Back Door Lock"
        value_template: "{{ is_state('lock.back_door_locked_11', 'locked') }}"
        turn_on:
          service: lock.lock
          data:
            entity_id: lock.back_door_locked_11
        turn_off:
          service: lock.unlock
          data:
            entity_id: lock.back_door_locked_11