# Play a sound on the RPi speaker when a door is opened.
alias: "Door Opened"
trigger:
  platform: state
  entity_id: group.sensors
  to: 'on'
condition:
  condition: time
  after: '07:00:00'
  before: '20:30:00'
action:
  - service: media_player.play_media
    data: 
      entity_id: media_player.speaker_1
      media_content_id: '/home/homeassistant/.homeassistant/Store_Door_Chime.wav'
      media_content_type: 'music'      