# Turn living room lamp off at 11:30PM
alias: "Living Room Lamp and Outdoor Lights off at 11:30PM"
trigger:
  platform: time
  at: '23:30:00'
action:
  service: light.turn_off
  entity_id: group.scheduled_lights