# Lock Front Door 1 minute after door is closed
alias: "Lock Door when closed"
trigger:
  platform: state
  entity_id: binary_sensor.front_door_sensor_opened
  to: 'off'
  for:
    minutes: 2
action:
  service: lock.lock
  entity_id: lock.front_door_locked_10