# Receive a phone call from IFTTT when smoke is detected
alias: "Smoke Alarm"
trigger:
  platform: state
  entity_id: group.nest_smoke_status
  to: 'Emergency'
# condition:
  # condition: and
  # conditions:
    # - condition: state
      # entity_id: 'group.family'
      # state: 'not_home'
    # - condition: state
      # entity_id: 'input_boolean.alarm_state'
      # state: 'on'
action:
  service: ifttt.trigger
  data: {"event":"nest_smoke_alarm"}