# Set Nest thermostat weekday schedule 
alias: "Nest thermostat weekday schedule"
trigger:
  - platform: time
    at: '06:45:00'
  - platform: time
    at: '17:00:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  service: script.turn_on
  entity_id: script.thermostat_home_22