# Set Nest thermostat weekend schedule 
alias: "Nest thermostat weekend schedule"
trigger:
  platform: time
  at: '07:45:00'
condition:
  condition: time
  weekday:
    - sat
    - sun
action:
  service: script.turn_on
  entity_id: script.thermostat_home_22