# Set Nest thermostat to "Home" when someone comes home during the day
alias: "Temp Weekday Home"
trigger:
  platform: state
  entity_id: group.family
  from: 'not_home'
condition:
  condition: time
  after: '07:00:00'
  before: '17:00:00'
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  service: script.turn_on
  entity_id: script.thermostat_home_22